---
- name: copy file webapp.war
  hosts: all
  become: true

  tasks:
    
    - name : copy file 
      copy:
        src: webapp/target/webapp.war
        dest: /opt/docker
    
    - name : Dockerfile
      shell: docker build -t houcem_demo /opt/docker/
    - name: stop previous version docker
      shell: docker stop houcem_demo
    - name: remove stopped container
      shell: docker rm -f houcem_demo	  
    - name: remove docker images
      shell: docker image rm -f houcem_demo
       
    - name: create docker image
      shell: docker run -d --name houcem_demo1 -p 8090:8080 houcem_demo