---
- name: copy file webapp.war
  hosts: all
  become: true

  tasks:
    
    - name : copy file 
      copy:
        src: webapp/target/webapp.war
        dest: /opt/docker

    - name: remove docker images
      shell: docker image rm -f houcem_demo 
    - name : Dockerfile
      shell: docker build -t houcem_demo /opt/docker/ 
    
